'use strict';
var a = [1, 2, 3, 4, 5];
var вырезано = a.splice(1, 2);
console.log(вырезано.join(','));
console.log(a.join(','));
var b = [1, 2, 3, 4, 5];
var вст = b.splice(2, 0, 10, 11);
console.log(вст.join(','));
console.log(b.join(','));
var c = [1, 2, 3, 4, 5];
var зам = c.splice(1, 2, 99);
console.log(зам.join(','));
console.log(c.join(','));
var d = [1, 2, 3, 4, 5];
var хвост = d.splice(-2);
console.log(хвост.join(','));
console.log(d.join(','));
var e = [1, 2, 3, 4, 5];
var пусто = e.splice(2);
console.log(пусто.join(','));
console.log(e.join(','));
var f = [1, 2, 3];
var много = f.splice(1, 100);
console.log(много.join(','));
console.log(f.join(','));
var g = [1, 2, 3];
var пустой = g.splice(1, 0);
console.log(пустой.length);
console.log(g.join(','));
