'use strict';
var s = new Set([1, 2, 3, 2, 1]);
console.log(s.size);
console.log(s.has(2));
console.log(s.has(9));
console.log(s.delete(2));
console.log(s.delete(9));
console.log(s.size);
var sc = new Set();
var ret = sc.add(10).add(20).add(10);
console.log(sc.size);
console.log(ret === sc);
for (var v of sc.values()) console.log(v);
var o1 = { x: 1 };
var o2 = { x: 1 };
var so = new Set([o1]);
console.log(so.has(o1));
console.log(so.has(o2));
var sn = new Set([NaN, NaN, 1]);
console.log(sn.size);
console.log(sn.has(NaN));
var sz = new Set([-0, 0, 1]);
console.log(sz.size);
for (var v2 of sz.values()) console.log(v2);
