'use strict';
var a = new Set([1, 2, 3, 4]);
var b = new Set([3, 4, 5, 6]);
for (var v of a.union(b).values()) console.log(v);
console.log('---');
for (var v of a.intersection(b).values()) console.log(v);
console.log('---');
for (var v of a.difference(b).values()) console.log(v);
console.log('---');
for (var v of a.symmetricDifference(b).values()) console.log(v);
console.log('---');
var sm = new Set([3, 4]);
console.log(sm.isSubsetOf(a));
console.log(a.isSubsetOf(sm));
console.log(a.isSupersetOf(sm));
console.log(sm.isSupersetOf(a));
var nd = new Set([7, 8]);
console.log(a.isDisjointFrom(nd));
console.log(a.isDisjointFrom(b));
