'use strict';
var m = new Map();
m.set('а', 1).set('б', 2).set('в', 3);
console.log(m.size);
console.log(m.get('б'));
console.log(m.has('а'));
console.log(m.has('нет'));
console.log(m.delete('а'));
console.log(m.delete('нет'));
console.log(m.size);
for (var k of m.keys()) console.log(k);
for (var v of m.values()) console.log(v);
for (var e of m.entries()) console.log(e[0] + '=' + e[1]);
var m2 = new Map([[1, 'один'], [2, 'два'], [3, 'три']]);
console.log(m2.get(1));
console.log(m2.size);
var o1 = { x: 1 };
var o2 = { x: 1 };
var mo = new Map();
mo.set(o1, 'первый');
mo.set(o2, 'второй');
console.log(mo.size);
console.log(mo.get(o1));
console.log(mo.get(o2));
