'use strict';
const re = /\d+/g;
const m1 = re.exec("a12b345c6");
console.log(m1[0]);
console.log(m1.index);
console.log(re.lastIndex);
const m2 = re.exec("a12b345c6");
console.log(m2[0]);
console.log(m2.index);
console.log(re.lastIndex);
const m3 = re.exec("a12b345c6");
console.log(m3[0]);
console.log(re.lastIndex);
const m4 = re.exec("a12b345c6");
console.log(m4);
console.log(re.lastIndex);
const m5 = re.exec("a12b345c6");
console.log(m5[0]);
console.log(re.lastIndex);
