'use strict';
const s = /\d/y;
s.lastIndex = 1;
const a = s.exec("a1b2");
console.log(a[0]);
console.log(s.lastIndex);
const b = s.exec("a1b2");
console.log(b);
console.log(s.lastIndex);
const g = /(?<year>\d{4})-(?<month>\d{2})/;
const m = g.exec("2026-06");
console.log(m[0]);
console.log(m[1]);
console.log(m[2]);
console.log(m.groups.year);
console.log(m.groups.month);
console.log(m.index);
const n = /(?<word>\w+)/;
const nm = n.exec("hi");
console.log(nm.groups.word);
