'use strict';
const с = "abcdef";
console.log(с.slice(1, 4));
console.log(с.slice(-2));
console.log(с.slice(-4, -1));
console.log(с.slice(4, 2));
console.log(с.slice(2, 100));
console.log(с.slice(-100, 3));
console.log(с.substring(1, 4));
console.log(с.substring(4, 2));
console.log(с.substring(-3, 2));
console.log(с.substring(2, 100));
console.log(с.at(0));
console.log(с.at(-1));
console.log(с.at(5));
console.log(с.at(6));
console.log(с.at(-6));
console.log(с.at(-7));
console.log(с.charAt(0));
console.log(с.charAt(6));
