[package]
name = "yps-dap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "yps-dap"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
yps-lexer.workspace = true
yps-parser.workspace = true
yps-interpreter.workspace = true
