use crate::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum KeywordKind {
    Gyy,
    Uchastkoviy,
    YasenHuy,
    Vilkoyvglaz,
    Ilivzhopuraz,
    Potreshchim,
    Go,
    Hare,
    Dvigay,
    Yopta,
    Otvechayu,
    Pravda,
    Lozh,
    Nol,
    Try,
    Catch,
    Finally,
    Throw,
    Switch,
    Case,
    Default,
    DoWhile,
    In,
    Undefined,
    Class,
    Extends,
    Super,
    New,
    This,
    Static,
    Typeof,
    Instanceof,
    GeneratorFn,
    Yield,
    Async,
    Await,
    Import,
    Export,
    From,
    Of,
    Delete,
    Void,
    Using,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OperatorKind {
    Plus,
    Minus,
    Multiply,
    Exponent,
    Divide,
    Modulo,
    Assign,
    PlusAssign,
    MinusAssign,
    MulAssign,
    DivAssign,
    ExponentAssign,
    Increment,
    Decrement,
    Equals,
    StrictEquals,
    NotEquals,
    StrictNotEquals,
    Less,
    Greater,
    LessOrEqual,
    GreaterOrEqual,
    And,
    Or,
    Not,
    NullishCoalescing,
    NullishAssign,
    AndAssign,
    OrAssign,
    Pipeline,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PunctuationKind {
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Colon,
    Dot,
    Spread,
    Question,
    OptionalChain,
    Arrow,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Identifier,
    Number,
    StringLiteral,
    Keyword(KeywordKind),
    Operator(OperatorKind),
    Punctuation(PunctuationKind),
    TemplateNoSub,
    TemplateHead,
    TemplateMiddle,
    TemplateTail,
    Eof,
    Unknown,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
